spring:
  profiles:
    active: local
  application:
    name: thumb-backend
  mvc:
    servlet:
      path: /api
  data:
    redis:
      database: 2
      host: ${suewei.redis.host}
      password: ${suewei.redis.password}
      connect-timeout: 5000
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${suewei.datasource.url}
    username: ${suewei.datasource.username}
    password: ${suewei.datasource.password}
springdoc:
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI访问路径
    tags-sorter: alpha      # 接口按字母排序
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs      # 接口JSON路径
    enabled: true
knife4j:
  enable: true
  setting:
    language: zh_cn
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true #驼峰命名

